---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(ggplot2)
library(magic)

```

Note that the following is a very hacky way to source this code. 

```{r}

# staCMRsetup
# sources STACMR functions, loads required packages, and links to java runtime library
# execute this program before doing anything else
bookinfo = 'Dunn, J. C. & Kalish, M. L. (2018). State-Trace Analysis. Springer.'
cat ('STACMR program library Version 21.02.2018\n')
cat ('Utility programs for use with the book:\n')
cat (paste0(bookinfo,'\n\n'))
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staSTATS.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staPLOT.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staMR.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staMRFIT.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staCMR.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staCMRFIT.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staPLOTBN.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staMRBN.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staCMRBN.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staCMRFITBN.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staMRFITBN.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/staCMRFITBN.R')

source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/Utility%20functions/staCMRx.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/Utility%20functions/gen2list.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/Utility%20functions/list2adj.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/Utility%20functions/adj2list.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/Utility%20functions/shrinkDiag.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/Utility%20functions/gen2listBN.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/Utility%20functions/staSTATSBN.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/Utility%20functions/BNframe2list.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/Utility%20functions/binSTATS.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/Utility%20functions/tiesort.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/Utility%20functions/LoftusMasson.R')

source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/java/jMR.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/java/jMRfits.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/java/jMRBNfits.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/java/jCMRxBNfits.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/java/jCMRx.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/java/jCMRBN.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/java/jCMRfitsx.R')
source ('https://raw.githubusercontent.com/michaelkalish/STA/master/STACMR-R/java/jCMRBN.R')


```



```{r}

data("delay")
vnames <- c("B1","B2","B3","B4")
y <- gen2list(data=delay, varnames=vnames)

delaystats <- staSTATS(delay, vnames)

staPLOT (data=delay, groups=list(c(1:4), c(5:8)),
         grouplabels=list("No delay","Delay"), axislabels = list("RB","II"))


```

```{r}

E <- list(c(1:4),c(5:8),c(5,1),c(6,2),c(7,3),c(8,4))

out2 <- staMR(data=delay, partial=E)
cbind(out2$x[[1]],out2$x[[2]])

```

```{r}
out1 = staCMR(data=delay, partial=E)

staPLOT (data=delay, groups=list(c(1:4), c(5:8)),
         grouplabels=list("No delay","Delay"), axislabels=list("RB","II"),
         pred=out1$x)

out = staCMRFIT(delay, partial=E, nsample=10000)


```

```{r}

data("dfie")

out = staCMRFITBN(dfie, partial=list(c(1:3),c(4:6)), nsample=10000)

staPLOTBN(dfie, subject=1, groups=list(c(1:3),c(4:6)),
          grouplabels=list("Upright", "Inverted"),
          axislabels=list("Faces","Houses"), pred = out$x)


```

